---
title: "Estimating Truth by Repetition: A Monte Carlo Simulation"
author: "Group 3: Andi Mellyn, Jessica Reyes, Hope Winsor"
format: revealjs
editor: visual
---

## Research Study

<br>

"Sample size for binary logistic prediction models: beyond events per variable criteria", Maarten et. al

*Statistical Methods in Medical Research*

-   analyzing out-of-sample accuracy in logistic regression

    -   Clinical simulation studies for outcomes like positive/negative for a disease

    -   want accurate predictions on new data

## Events Per Variable

*Events Per Variable* (EPV), a ratio of the number of events to the number of degrees of freedom

-   think signal to noise

-   used to decide the minimum sample size & maximum number of predictors to use in a study

-   standard is EPV ≥ 10

-   EPV has shown to be either too lenient or too strict depending on the modeling strategy & does not strongly relate to prediction accuracy

## Simulation Study

-   created more than 4,000 different combinations and over 12,000,000 datasets

    -   different combinations of EPV, event ratios, number and distribution of predictors, AUC, and predictor effects

-   7 different models

    -   Maximum Likelihood, backwards subset selection, Firth's penalized likelihood, heuristic shrinkage, Ridge, LASSO

-   6 predictive performance metrics

    -   rMPSE, MAPE, calibration slope, average calibration in large, $\Delta$AUC, Brier

## Our Implementation

### Questions

-   What effect does EPV have on out-of-sample prediction for logistic regression?

-   What effect does EPV have on out-of-sample prediction for non-parametric methods of binary classification?

-   Are there metrics that better estimate out-of-sample prediction? If so, which ones?

## Our Implementation

### Variation in Monte Carlo Study: Subset of original study

$3 \times 3 \times 2 \times 4$ factor study resulting in 72 distinct combinations simulated 10 times each

-   EPV (5, 10, 50), number of candidate predictors (P) (4, 8, 12), distribution of predictors (MVN(0), MVN(0.5)), beta patterns: (equal effect,1 strong, 1 noise, 1/2 noise)

-   predictive performance metrics: rMPSE, MAE, Brier

-   Training data set has $N = \frac{EPV * P}{Pr(Y = 1)}$ data points

-   Testing dataset has $N^* = \frac{5000}{Pr(Y = 1)}$ data points

## Maximum Likelihood

## Ridge Logistic Regression

## Random Forest

## Maximum Likelihood vs. Ridge

## Random Forest vs. MLE & Ridge

```{r}

```

## Conclusion

## 
