---
title: "Estimating Truth by Repetition: A Monte Carlo Simulation"
author: "Group 3: Andi Mellyn, Jessica Reyes, Hope Winsor"
format: revealjs
editor: visual
---

## Research Study

<br>

Sample size for binary logistic prediction models: beyond events per variable criteria, Maarten et. al

*Statistical Methods in Medical Research*

## Simulation Study

<br>

Clinical simulation studies for binary outcomes

-   want accurate predictions on new data

-   *Events Per Variable* (EPV), a ratio of the number of events to the number of degrees of freedom

    -   think signal to noise

    -   used to decide the minimum sample size & maximum number of predictors to use in a study

    -   standard is EPV ≥ 10

-   EPV has shown to be either too lenient or too strict depending on the modeling strategy & does not strongly relate to prediction accuracy

Simulation study:

-   studies the influence of EPV, the events fraction, & the number of possible predictors

-   predictive performance of correlations, distributions of possible predictor variables, & predictor effects on new simulated sample data are compared

Comparison methods:

-   rMPSE

-   calibration slope

-   AUC

## Simulation Study

-   created more than 4,000 different combinations and over 12,000,000 datasets

    -   different combinations of EPV, event ratios, number and distribution of predictors, AUC, and predictor effects

-   7 different models

    -   Maximum Likelihood, backwards subset selection, Firth's penalized likelihood, heuristic shrinkage, Ridge, LASSO

## Our Implementation

### Questions

-   What effect does EPV have on out-of-sample prediction for logistic regression?

-   What effect does EPV have on out-of-sample prediction for non-parametric methods of binary classification?

-   Are there metrics that better estimate out-of-sample prediction? If so, which ones?

### Variation in Monte Carlo Study: Subset of original study

-   EPV values

-   number of predictors

-   correlation in the predictors

-   beta patterns

-   event fraction -\> kept stable

## Maximum Likelihood

<br>

## Ridge Logistic Regression

<br>

-   adds an L2 penalty to shrink the coefficients toward zero

-   reduces overfitting when predictors are correlated or sample size is small

## Random Forest

<br>

## Maximum Likelihood vs. Ridge

<br>

## Random Forest vs. MLE & Ridge

<br>

## Results

<br>

## Conclusion

<br>

Outcome:

-   research study indicates that EPV does not have a strong relation with the metrics of predictive performance

-   suggest using 3 factors instead: number of predictors, total sample size, & the events fraction (a ratio of positive outcomes over the total outcomes)

## 
