---
title: "MLE_Ridge_Forest"
author: "Group 3"
date: "2025-12-07"
output: html_document
---

\colorlet{shadecolor}{gray!10}
```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(MASS)
library(GGally)
library(tidymodels)
library(glmnet)
library(pROC)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, tidy = FALSE)
```
\newcommand{\hstart}{ \colorlet{shadecolor}{green!20}
\begin{shaded} }
\newcommand{\hstop}{  \end{shaded} \colorlet{shadecolor}{gray!10}}

\hstart

# MLE vs. Ridge Regression vs. Random Forest

We compare the three modeling approaches under the same Monte Carlo simulation design used earlier.

\hstop

```{r}
# loading Monte Carlo results datasets

mle_df <- read.csv("MLE_Simulation.csv")
ridge_df <- read.csv("results_files/ridge_mc_testing_results.csv")

```

```{r}
# creating a master table
all_results <- bind_rows(mle_df, ridge_df)
head(all_results)

```

\hstart

### Boxplots
AUC boxplot distribution

\hstop

```{r}
# AUC
ggplot(all_results, aes(x = model, y = AUC, fill = model)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  facet_grid(EPV ~ P) +
  labs(title = "AUC Distribution Across Methods",
       x = "Model", 
       y = "AUC")

```

```{r}
# Briar
ggplot(all_results, aes(x = model, y = Brier, fill = model)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  facet_grid(EPV ~ P) +
  labs(title = "Brier Score Distribution Across Methods", 
       x = "Model", 
       y = "Brier Score")

```

```{r}
# compute means for heatmap
# method * EPV * P

mean_results <- all_results |>
  group_by(model, EPV, P) |>
  summarise(mean_AUC = mean(AUC), mean_Brier = mean(Brier), .groups = "drop")

mean_results

 
```

```{r}
# heatmap for mean AUC

ggplot(mean_results, aes(x = factor(P), y = factor(EPV), fill = mean_AUC)) +
  geom_tile() +
  facet_wrap(~ model) + 
  scale_fill_viridis_c(option = "plasma") +
  labs(title = "Heatmap of Mean AUC",
    x = "Number of Predictors (P)",
    y = "EPV",
    fill = "Mean AUC"
  )

```

```{r}
ggplot(mean_results, aes(x = factor(P), y = factor(EPV), fill = mean_Brier)) +
  geom_tile() +
  facet_wrap(~ model) + 
  scale_fill_viridis_c(option = "magma") +
  labs(title = "Heatmap of Mean Brier Score",
    x = "Number of Predictors (P)",
    y = "EPV",
    fill = "Mean Brier"
  )

```

